/**
 * SignalStay interior pages — a shared content system for the reference-inspired route family.
 * Page structure stays consistent across verticals while each route gets its own signal, proof,
 * and operating language. No fabricated customer reviews or ratings are used.
 */
import { ArrowRight, ArrowUpRight, BarChart3, Check, ChevronRight, Clock3, Layers3, Mail, MapPin, MessageCircle, Play, ShieldCheck, Sparkles, TrendingUp, Users, type LucideIcon } from "lucide-react";
import { Link } from "wouter";
import { SiteFooter, SiteHeader } from "@/components/SiteShell";

const markImage = "/manus-storage/signalstay-mark_2126229d.png";
const analyticsImage = "/manus-storage/signalstay-analytics_9510ba1f.jpg";
const commsImage = "/manus-storage/signalstay-comms_d7b29c13.jpg";
const closingImage = "/manus-storage/signalstay-closing_8add029d.jpg";

export type PageKind = "str" | "hotel" | "case-studies" | "resources" | "about" | "partners" | "contact" | "careers" | "book" | "detail";

type PageConfig = {
  kind: PageKind;
  eyebrow: string;
  title: string;
  emphasis: string;
  intro: string;
  primary: string;
  primaryHref: string;
  secondary?: string;
  secondaryHref?: string;
  statLabel: string;
  statValue: string;
  statNote: string;
  panelTitle: string;
  panelCopy: string;
  bullets: string[];
};

const configs: Record<string, PageConfig> = {
  "/str": { kind: "str", eyebrow: "For short-term rental operators", title: "Make every listing", emphasis: "pull its weight.", intro: "SignalStay turns the daily revenue work behind a portfolio into one clear operating rhythm: rank, rate, content, channel mix, and the decision that connects them.", primary: "Explore the STR operating model", primaryHref: "/str/revenue-management", secondary: "Run a portfolio health check", secondaryHref: "/str/revenue-health-check", statLabel: "Listings watched", statValue: "25k+", statNote: "Across multi-market short-term rental portfolios", panelTitle: "The portfolio is a system, not a spreadsheet.", panelCopy: "A single listing can be priced correctly and still lose visibility. We connect the signals that tell you why, then assign the next action to the right lever.", bullets: ["Daily rank and comp-set visibility monitoring", "Channel-specific content and promotion strategy", "Pricing direction calibrated to where each listing sits"] },
  "/hotel": { kind: "hotel", eyebrow: "For independent hotels", title: "Run the revenue desk", emphasis: "with more signal.", intro: "Bring pricing, OTA visibility, distribution, and commercial context into one operating layer—without replacing the tools your team already trusts.", primary: "Explore hotel operations", primaryHref: "/hotel/revenue-management", secondary: "See OTA ranking systems", secondaryHref: "/hotel/ota-optimization", statLabel: "Revenue layers", statValue: "03", statNote: "Visibility, pricing, and distribution in one rhythm", panelTitle: "Your stack should work harder together.", panelCopy: "We sit above the tools already in place, directing the commercial decisions that no single pricing engine or channel manager can see alone.", bullets: ["Direct and OTA channel mix managed together", "Rate strategy that respects market and placement", "A daily view your commercial team can act on"] },
  "/str/revenue-management": { kind: "detail", eyebrow: "STR operations / revenue management", title: "Pricing is only useful", emphasis: "when rank agrees.", intro: "Dynamic pricing can move the rate. SignalStay manages the conditions that decide whether a guest sees it, trusts it, and books it.", primary: "Book a signal review", primaryHref: "/book-a-call-with-our-experts", secondary: "See OTA optimization", secondaryHref: "/str/ota-optimization", statLabel: "Signal window", statValue: "18d", statNote: "Illustrative lead time between rank and booking pace", panelTitle: "A rate is a decision, not a strategy.", panelCopy: "We calibrate floors, ceilings, length-of-stay rules, promotions, and booking pace to the visibility position each listing has actually earned.", bullets: ["Dynamic pricing direction and guardrails", "Gap-night and length-of-stay strategy", "Promotion decisions tied to incremental yield"] },
  "/str/ota-optimization": { kind: "detail", eyebrow: "STR operations / OTA optimization", title: "Visibility is a lever", emphasis: "you can operate.", intro: "Airbnb, Booking.com, Vrbo, and Expedia each reward different behavior. We build the playbook for each channel and keep it moving.", primary: "Audit your channel setup", primaryHref: "/book-a-call-with-our-experts", secondary: "See ranking intelligence", secondaryHref: "/str/ranking-intelligence", statLabel: "Channels", statValue: "04", statNote: "Channel-specific operating patterns, not one default setup", panelTitle: "Every OTA has its own weather.", panelCopy: "We tune content, promotions, response signals, parity, and placement together so your portfolio earns visibility without trading away pricing power.", bullets: ["Channel-specific listing and promotion strategy", "Parity and placement monitoring", "Active management of major OTA ranking signals"] },
  "/str/revenue-health-check": { kind: "detail", eyebrow: "STR operations / portfolio health check", title: "Find the leak", emphasis: "before it scales.", intro: "A portfolio can grow while the operation quietly loses yield. This health check maps where visibility, pricing, and distribution are drifting apart.", primary: "Request a health check", primaryHref: "/book-a-call-with-our-experts", secondary: "Explore portfolio operations", secondaryHref: "/str", statLabel: "First read", statValue: "30d", statNote: "A practical momentum window for ranking and pace", panelTitle: "A useful audit ends with a move.", panelCopy: "We turn the diagnostic into a prioritized set of actions, with the signal, the owner, and the expected direction visible to your team.", bullets: ["Listing and channel signal scan", "Rate and availability guardrail review", "A prioritized action map for the next operating cycle"] },
  "/hotel/revenue-management": { kind: "detail", eyebrow: "Hotel operations / revenue management", title: "Make demand visible", emphasis: "to the whole team.", intro: "A modern hotel revenue desk needs more than a forecast. It needs a daily operating view that connects demand, placement, rate, and commercial intent.", primary: "Talk to a revenue expert", primaryHref: "/book-a-call-with-our-experts", secondary: "See hotel OTA ranking", secondaryHref: "/hotel/ota-optimization", statLabel: "Operating layers", statValue: "03", statNote: "Commercial context shared across the revenue desk", panelTitle: "The best decision is already in the stack.", panelCopy: "SignalStay interprets your market and placement signals so your team can spend less time reconciling systems and more time acting on the opportunity.", bullets: ["Demand and comp-set movement in one view", "Rate plan and restriction strategy", "Clear actions for commercial and operations teams"] },
  "/hotel/ota-optimization": { kind: "detail", eyebrow: "Hotel operations / OTA ranking", title: "Win the search", emphasis: "before the click.", intro: "Hotel visibility is shaped by more than price. We manage the content, channel, promotion, and conversion signals that decide who gets considered first.", primary: "Review your OTA mix", primaryHref: "/book-a-call-with-our-experts", secondary: "See hotel revenue management", secondaryHref: "/hotel/revenue-management", statLabel: "Signal mix", statValue: "1:1", statNote: "Visibility decisions matched to each channel context", panelTitle: "Distribution is a commercial decision.", panelCopy: "We coordinate channel weight, offer structure, content, and rate positioning so the right channel does the right job for the property.", bullets: ["Channel-specific content and offer structure", "Placement and conversion signal review", "Distribution actions tied to property goals"] },
  "/case-studies": { kind: "case-studies", eyebrow: "Customer signals", title: "Results start", emphasis: "with a better read.", intro: "Every portfolio begins from a different position. The repeatable pattern is simple: understand the signal, act on the right lever, keep the operation moving.", primary: "Talk through your starting point", primaryHref: "/book-a-call-with-our-experts", secondary: "See the portfolio signal view", secondaryHref: "/case-studies/portfolio-signals", statLabel: "Outcome lens", statValue: "01", statNote: "Rank direction before revenue projection", panelTitle: "No performance theatre. Just the operating pattern.", panelCopy: "We show the decisions behind a change in direction—what moved, what was adjusted, and what the team could see earlier next time.", bullets: ["Before / after operating snapshots", "Decision trail for pricing and channel changes", "Illustrative data clearly labelled for discussion"] },
  "/case-studies/portfolio-signals": { kind: "case-studies", eyebrow: "Customer signals / portfolio view", title: "Read the portfolio", emphasis: "as one system.", intro: "The useful customer story is not a quote on a page. It is the signal trail: where visibility shifted, how the team responded, and what changed next.", primary: "Map your signal trail", primaryHref: "/book-a-call-with-our-experts", secondary: "Return to customer signals", secondaryHref: "/case-studies", statLabel: "Signal trail", statValue: "28d", statNote: "A simple operating window for seeing momentum", panelTitle: "Make the next move legible.", panelCopy: "Portfolio-level visibility makes the exception visible without losing the property-level detail needed to take action.", bullets: ["Rank direction across a portfolio", "Booking pace and pricing context side by side", "Actions grouped by channel, market, and owner"] },
  "/resources": { kind: "resources", eyebrow: "Signal library", title: "Useful thinking for", emphasis: "busy operators.", intro: "Short notes, practical playbooks, and plain-English explanations for the decisions that sit between a rate and a reservation.", primary: "Read the journal", primaryHref: "/resources/guides", secondary: "Talk to an operator", secondaryHref: "/book-a-call-with-our-experts", statLabel: "Format", statValue: "03", statNote: "Journal notes, guides, and live sessions", panelTitle: "A resource should change the next conversation.", panelCopy: "We keep the ideas close to the work: rank, channel, pricing, distribution, and the context your team needs to make a better call.", bullets: ["Operator notes without the jargon", "Guides you can use in the next revenue meeting", "Sessions that connect strategy to execution"] },
  "/resources/guides": { kind: "resources", eyebrow: "Signal library / guides", title: "Keep the playbook", emphasis: "close to the work.", intro: "Step-by-step frameworks for turning an unclear performance signal into a decision your team can own.", primary: "Browse the guide topics", primaryHref: "/resources", secondary: "Book a working session", secondaryHref: "/book-a-call-with-our-experts", statLabel: "Guide style", statValue: "01", statNote: "One clear operating question at a time", panelTitle: "The best guide has a next action.", panelCopy: "Use the same language across your revenue, operations, and distribution teams to turn signal review into operating habit.", bullets: ["Search-rank reading basics", "Channel-specific revenue questions", "Practical review cadence templates"] },
  "/resources/webinars": { kind: "resources", eyebrow: "Signal library / webinars", title: "Hear how operators", emphasis: "make the call.", intro: "Live and on-demand conversations about the details that determine whether a revenue strategy actually reaches the listing.", primary: "Explore sessions", primaryHref: "/resources", secondary: "Bring a question", secondaryHref: "/book-a-call-with-our-experts", statLabel: "Session style", statValue: "LIVE", statNote: "Conversation before presentation", panelTitle: "The useful bit is usually the trade-off.", panelCopy: "Sessions are built around the judgment calls operators make when visibility, rate, and distribution are moving at different speeds.", bullets: ["Recorded operator conversations", "Practical question-led sessions", "Context for revenue and commercial teams"] },
  "/about": { kind: "about", eyebrow: "About SignalStay", title: "A clearer operating layer", emphasis: "for hospitality revenue.", intro: "SignalStay exists for the teams who know that a calendar is an outcome. The useful work starts earlier, in the signals that shape who gets seen and what guests choose.", primary: "Meet the operating model", primaryHref: "/str", secondary: "Talk to the team", secondaryHref: "/contact", statLabel: "Our stance", statValue: "EARLY", statNote: "Read the signal before it becomes a problem", panelTitle: "Precise does not have to feel cold.", panelCopy: "We combine analytical discipline with the calm, direct communication hospitality teams need when the market moves faster than the meeting calendar.", bullets: ["Operator-first language and decisions", "Clear ownership for every action", "No new dashboard unless it earns its place"] },
  "/partners": { kind: "partners", eyebrow: "Partners & integrations", title: "Work on top of", emphasis: "the stack you trust.", intro: "SignalStay complements your pricing tool, PMS, channel manager, and communication channels. We connect the context and keep the next move visible.", primary: "Discuss your stack", primaryHref: "/book-a-call-with-our-experts", secondary: "Explore the operating model", secondaryHref: "/str", statLabel: "Integration stance", statValue: "ON TOP", statNote: "Strategy and execution around your existing tools", panelTitle: "Replace the handoff, not the system.", panelCopy: "Your tools already hold valuable signals. We work around them to bring the operating decisions into one rhythm.", bullets: ["Pricing and revenue management systems", "PMS and channel manager context", "Slack, WhatsApp, and team communication"] },
  "/contact": { kind: "contact", eyebrow: "Contact SignalStay", title: "Bring us the signal", emphasis: "you want to understand.", intro: "Tell us where the calendar feels unclear: a ranking drop, a portfolio that grew too fast, or a channel that is not earning its place.", primary: "Book a signal review", primaryHref: "/book-a-call-with-our-experts", secondary: "Explore the operating model", secondaryHref: "/str", statLabel: "First conversation", statValue: "30m", statNote: "A direct conversation about your current setup", panelTitle: "No pitch deck required.", panelCopy: "A useful first conversation starts with the property, market, and signal you are already watching.", bullets: ["Portfolio size and market context", "Current tools and revenue cadence", "The question your team wants answered"] },
  "/careers": { kind: "careers", eyebrow: "Careers at SignalStay", title: "Build the layer", emphasis: "operators can trust.", intro: "We are building a more legible way to run hospitality revenue: less tab switching, fewer handoffs, better decisions made earlier.", primary: "Start a conversation", primaryHref: "/contact", secondary: "See our operating principles", secondaryHref: "/about", statLabel: "Working style", statValue: "CLEAR", statNote: "Direct thinking, kind communication, visible ownership", panelTitle: "Good work is easier to scale when it is legible.", panelCopy: "Bring curiosity, attention to detail, and respect for the people who have to operate what we build.", bullets: ["Own the outcome, not just the task", "Make the signal easy to see", "Keep the human context in the system"] },
  "/book-a-call-with-our-experts": { kind: "book", eyebrow: "Free signal review", title: "See what is moving", emphasis: "before the calendar.", intro: "Share a few details and we will use the first conversation to map the signals behind your current revenue operation.", primary: "Submit your review request", primaryHref: "#request", secondary: "Explore the operating model", secondaryHref: "/str", statLabel: "No commitment", statValue: "FREE", statNote: "A useful conversation before a commercial decision", panelTitle: "The first output is clarity.", panelCopy: "We will look at your current channel mix, pricing setup, portfolio shape, and the signal that prompted you to reach out.", bullets: ["Current portfolio and market", "Tools already in place", "The revenue question you want answered"] },
};

const fallback: PageConfig = { kind: "detail", eyebrow: "SignalStay operations", title: "A better read", emphasis: "changes the next move.", intro: "Explore the operating layer that connects visibility, pricing, and distribution into a more useful daily rhythm.", primary: "Book a signal review", primaryHref: "/book-a-call-with-our-experts", secondary: "Return to the operating model", secondaryHref: "/str", statLabel: "SignalStay", statValue: "01", statNote: "One operating rhythm for the levers behind revenue", panelTitle: "Revenue is a connected operation.", panelCopy: "We help teams see what is moving, decide what matters, and act before the calendar has to explain it.", bullets: ["Visibility before booking pace", "Pricing with channel context", "Actions your team can own"] };

function getConfig(path: string): PageConfig {
  return configs[path] || fallback;
}

const iconFor = (index: number): LucideIcon => [TrendingUp, BarChart3, Layers3, ShieldCheck, Sparkles, Users][index % 6];

function SignalDiagram({ kind }: { kind: PageKind }) {
  return <div className={`interior-diagram interior-diagram--${kind}`}>
    <div className="interior-diagram-glow" />
    <div className="diagram-orbit diagram-orbit--one" /><div className="diagram-orbit diagram-orbit--two" />
    <div className="diagram-center"><img src={markImage} alt="" /><span>{kind === "hotel" ? "revenue desk" : kind === "resources" ? "library" : kind === "book" ? "review" : kind === "partners" ? "stack" : "portfolio"}</span><strong>{kind === "resources" ? "notes" : kind === "book" ? "brief" : "signal"}</strong></div>
    <div className="diagram-pill diagram-pill--one"><TrendingUp size={14} /><span>{kind === "hotel" ? "pace" : kind === "resources" ? "read" : "rank"}</span><b>{kind === "resources" ? "06" : "+12"}</b></div>
    <div className="diagram-pill diagram-pill--two"><BarChart3 size={14} /><span>{kind === "hotel" ? "rate" : kind === "resources" ? "guide" : "pace"}</span><b>{kind === "hotel" ? "ADR" : "↑ 18d"}</b></div>
    <div className="diagram-pill diagram-pill--three"><Layers3 size={14} /><span>{kind === "partners" ? "stack" : kind === "book" ? "brief" : "mix"}</span><b>{kind === "partners" ? "ON TOP" : "04 OTA"}</b></div>
    <div className="diagram-foot">{kind === "resources" ? "read / apply / repeat" : kind === "book" ? "question / context / next move" : kind === "hotel" ? "commercial desk / daily" : "one operating rhythm / daily"}</div>
  </div>;
}

function SignalStrip({ config }: { config: PageConfig }) {
  return <div className="interior-proof-strip"><div><span>Signal window</span><strong>{config.statValue}</strong><small>{config.statNote}</small></div><div><span>Visibility</span><strong>#04</strong><small>Illustrative rank position</small></div><div><span>Next action</span><strong>01</strong><small>One prioritized move</small></div></div>;
}

function ActionPanel({ config }: { config: PageConfig }) {
  return <div className="interior-action-panel"><div className="action-panel-head"><span className="eyebrow eyebrow--violet">Operating note</span><span className="panel-live"><i /> signal live</span></div><h2>{config.panelTitle}</h2><p>{config.panelCopy}</p><ul>{config.bullets.map((item) => <li key={item}><Check size={14} />{item}</li>)}</ul><Link className="text-link text-link--light" href={config.primaryHref}>{config.primary} <ArrowUpRight size={16} /></Link></div>;
}

function TopicGrid({ kind }: { kind: PageKind }) {
  const topicSets: Record<PageKind, { title: string; description: string }[]> = {
    str: ["Rank by listing", "Pricing windows", "Channel contribution", "Booking pace", "Alert ownership", "Portfolio roll-up"].map((title) => ({ title, description: "A portfolio signal tied to the next operating action." })),
    hotel: ["Demand pace", "Rate plan health", "Direct / OTA mix", "Comp-set position", "Commercial handoff", "Daily desk view"].map((title) => ({ title, description: "A revenue-desk input for a more confident commercial call." })),
    resources: ["Rank before bookings", "A practical rate review", "The channel mix question", "How to read a visibility drop", "Owner-ready revenue language", "The weekly operating rhythm"].map((title) => ({ title, description: "A short, useful lens for the next revenue conversation." })),
    "case-studies": ["Portfolio direction", "Search position", "Booking pace", "Rate confidence", "Channel contribution", "Action ownership"].map((title) => ({ title, description: "A decision trail, not a decorative success story." })),
    partners: ["Pricing engines", "PMS context", "Channel managers", "OTA signals", "Communication layers", "Reporting systems"].map((title) => ({ title, description: "A connected layer that makes the existing stack more useful." })),
    book: ["Portfolio context", "Current toolset", "Signal under review", "Market position", "Operating cadence", "Next best action"].map((title) => ({ title, description: "A question to bring into the first working conversation." })),
    about: ["Operator language", "Visible ownership", "Calm execution", "Human context", "Useful systems", "Earlier decisions"].map((title) => ({ title, description: "A principle we use to keep the work legible." })),
    careers: ["Clear thinking", "Visible ownership", "Kind communication", "Small signals", "Useful craft", "Shared momentum"].map((title) => ({ title, description: "A working principle for building the operating layer." })),
    contact: ["Portfolio context", "Market position", "Current toolset", "Signal under review", "Operating cadence", "Next conversation"].map((title) => ({ title, description: "A practical input for a more useful first conversation." })),
    detail: ["Visibility", "Pricing", "Distribution", "Alerts", "Content", "Reporting"].map((title) => ({ title, description: "One connected input in the operating rhythm." })),
  };
  const topics = topicSets[kind] || topicSets.detail;
  return <div className={`topic-grid topic-grid--${kind}`}>{topics.map((topic, index) => { const Icon = iconFor(index); return <article key={topic.title}><span className="topic-index">0{index + 1}</span><span className="topic-icon"><Icon size={17} /></span><h3>{topic.title}</h3><p>{topic.description}</p><ChevronRight className="topic-arrow" size={15} /></article>; })}</div>;
}

function BookingForm() {
  return <form id="request" className="booking-form" onSubmit={(event) => { event.preventDefault(); window.alert("Thanks — your signal review request is ready for the SignalStay team."); }}><div className="form-heading"><span className="eyebrow">Request a review</span><h2>Start with the signal.</h2><p>No commitment. Just enough context for a useful first conversation.</p></div><label>Name<input required name="name" placeholder="Your name" /></label><label>Business email<input required type="email" name="email" placeholder="name@company.com" /></label><label>Portfolio type<select name="type" defaultValue="short-term-rentals"><option value="short-term-rentals">Short-term rental portfolio</option><option value="hotel">Independent hotel</option><option value="mixed">Mixed portfolio</option></select></label><label>What are you watching right now?<textarea name="message" placeholder="A rank drop, pricing question, channel mix issue…" /></label><button className="button button--violet" type="submit">Submit review request <ArrowUpRight size={17} /></button><small>By submitting, you are asking SignalStay to contact you about this review. No fabricated results or guarantees are implied.</small></form>;
}

export default function ContentPage({ path }: { path: string }) {
  const config = getConfig(path);
  const isBook = config.kind === "book";
  return <div className="signalstay-site interior-site"><SiteHeader /><main>
    <section className="interior-hero"><div className="interior-hero-grid" /><div className="content-frame interior-hero-inner"><div className="interior-copy"><p className="eyebrow eyebrow--violet"><span className="eyebrow-pulse" />{config.eyebrow}</p><h1>{config.title}<br /><em>{config.emphasis}</em></h1><p className="interior-intro">{config.intro}</p><div className="hero-actions"><Link className="button button--violet" href={config.primaryHref}>{config.primary} <ArrowUpRight size={17} /></Link>{config.secondary && config.secondaryHref && <Link className="button button--ghost-light" href={config.secondaryHref}>{config.secondary} <ArrowRight size={17} /></Link>}</div><div className="hero-footnote"><span className="status-dot" />SignalStay / {config.kind === "detail" ? "operating layer" : config.kind}</div></div><SignalDiagram kind={config.kind} /></div></section>
    <SignalStrip config={config} />
    <section className="interior-intro-section"><div className="content-frame interior-two-col"><div className="section-kicker"><span className="section-number">01</span><span>{config.eyebrow}</span></div><div><p className="eyebrow">The operating question</p><h2>{config.panelTitle}</h2><p className="section-lede">{config.panelCopy} The signal gets useful when the team can see what changed, understand what it affects, and decide what happens next without stitching together five different views.</p><div className="mini-rule"><span /><span /><span /></div></div></div></section>
    <section className="interior-dark-section"><div className="content-frame"><div className="interior-heading-row"><div><p className="eyebrow eyebrow--violet">The signal map</p><h2>One question.<br /><em>Six connected inputs.</em></h2></div><p>Visibility, rate, content, channel mix, booking pace, and alerts—organized around the decision your team needs to make.</p></div><TopicGrid kind={config.kind} /></div></section>
    <section className="interior-action-section"><div className="content-frame action-layout"><ActionPanel config={config} /><div className="interior-image-panel" style={{ backgroundImage: `linear-gradient(90deg, rgba(8, 13, 34, .9), rgba(8, 13, 34, .12)), url(${config.kind === "resources" ? commsImage : analyticsImage})` }}><div className="image-panel-label"><span className="live-chip"><span /> live operating view</span><strong>{config.statLabel}</strong></div><div className="image-panel-chart"><div className="chart-bar chart-bar--one" /><div className="chart-bar chart-bar--two" /><div className="chart-bar chart-bar--three" /><div className="chart-bar chart-bar--four" /><div className="chart-bar chart-bar--five" /><svg viewBox="0 0 500 150" preserveAspectRatio="none" aria-hidden="true"><path d="M0 128 C55 126, 72 94, 118 105 S188 88, 236 100 S287 57, 335 72 S411 45, 500 20" /></svg></div><div className="image-panel-foot"><span>rank direction</span><strong>↑ 12 positions</strong></div></div></div></section>
    {isBook ? <section className="booking-section"><div className="content-frame booking-layout"><div><p className="eyebrow eyebrow--violet">Free / no commitment</p><h2>A clearer first<br /><em>conversation.</em></h2><p className="section-lede">The first conversation is not a product tour. It is a practical read on the signal your team is already trying to interpret.</p><div className="booking-points"><span><Clock3 size={16} />30 minutes</span><span><MessageCircle size={16} />Operator-led</span><span><ShieldCheck size={16} />No commitment</span></div></div><BookingForm /></div></section> : <section className="interior-image-section"><div className="content-frame editorial-panel"><div className="editorial-copy"><p className="eyebrow">The daily difference</p><h2>Catch the change<br /><em>while it is still small.</em></h2><p className="section-lede">The teams who move first do not have perfect information. They have a useful signal, a clear owner, and a cadence that turns observation into action.</p><Link className="text-link" href={config.primaryHref}>Continue the conversation <ArrowUpRight size={16} /></Link></div><div className="editorial-image" style={{ backgroundImage: `linear-gradient(90deg, rgba(8, 13, 34, .12), rgba(8, 13, 34, .18)), url(${closingImage})` }}><span className="editorial-stamp">SIGNAL / 01</span></div></div></section>}
    <section className="interior-cta" style={{ backgroundImage: `linear-gradient(90deg, rgba(8, 13, 34, .96), rgba(8, 13, 34, .65)), url(${closingImage})` }}><div className="content-frame"><p className="eyebrow eyebrow--violet">A better read changes the next move</p><h2>See what is moving<br /><em>before the calendar.</em></h2><Link className="button button--violet" href="/book-a-call-with-our-experts">Book a signal review <ArrowUpRight size={17} /></Link></div></section>
  </main><SiteFooter /></div>;
}

export { getConfig };
